enum Actions {
  FETCH_STARTED = "PLAYLIST/FETCH_STARTED",
  FETCH_ERROR = "PLAYLIST/FETCH_ERROR",
  STORE_RESULTS = "PLAYLIST/STORE_RESULTS",
  RESET_FETCH = "PLAYLIST/RESET_FETCH",
}

export default Actions;
